[package]
name = "seda-chains"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
near-jsonrpc-client = { workspace = true }
near-jsonrpc-primitives = { workspace = true }
near-primitives = { workspace = true }
tokio = { workspace = true }
seda-config = { workspace = true }
seda-runtime-sdk = { workspace = true }
near-crypto = { workspace = true }
thiserror = { workspace = true }
